---
name: KB link checker

on:
  push:
  # schedule:
  #   - cron: "0 0 * * 0"

jobs:
  kb-broken-link-checker:
    name: Check KB broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          docker run raviqqe/muffet --color=always -c 8 -t 200 \
            --exclude "https://mariadb.com" \
            --exclude "https://twitter.com" \
            --exclude "https://www.linkedin.com" \
            --exclude "http://kb-mirror.mariadb.com/kb/en/+questions" \
            --exclude "https://github.com/MariaDB/server/commit" \
            --exclude "http://kb-mirror.mariadb.com/kb/en/library/mariadb-server" \
            http://kb-mirror.mariadb.com/kb/en/library/documentation
